### ISSUE TITLE
Brisanjem COST ne brise se odometar slog

### ISSUE THREAD

**Issue by gumpforrest** [nemanja-d/fleet#36]
Primjetio sam kada sam obrisao fuel log da se nije izbrsaio odometer, sto je prozrokovalo da vehicle nema dobar odometer sto je dalje prouzrokovalo nepravilne ALERTE servisa

+provjeriti ostale tipove cost-a

**Comment by nemanja-d** [comment]
U fleet_extend sam redefinisao unlink za fleet.vehicle.cost u kojoj se brise odometer_id ako postoji
